name: YukiMusic
main: io.github.yukileafx.yukimusic.YukiMusic
version: 0.0.5

commands:
  play-nbs-url:
    usage: /play-nbs-url <URL>
    permission: yukimusic.command.play-nbs-url
permissions:
  yukimusic.command.play-nbs-url:
    default: true
